import { describe, it, expect } from "bun:test";
import {
  AUGMENT_CATALOG,
  resolveCatalogEntry,
  validAugmentSpecifiers,
} from "../../src/cli/augment-catalog";

describe("augment catalog", () => {
  it("turnControl is registered in the catalog", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "turnControl");
    expect(entry).toBeDefined();
    expect(entry?.label).toMatch(/turn[- ]?control/i);
    expect(entry?.required).toBe(true);
    // After ADR-025 + PR α task 2, turnControl ships a bundled skill folder.
    expect(entry?.hasSkill).toBe(true);
  });

  it("turnControl uses its canonical type as defaultName", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "turnControl");
    expect(entry?.defaultName).toBe("turnControl");
  });

  it("catalog includes a visitorAuth entry with required env vars", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "visitorAuth");
    expect(entry).toBeTruthy();
    // AGENTMAIL_* are no longer listed by default — the catalog ships with
    // `agentMail.transport: "console"` so AgentMail creds aren't needed unless
    // the operator switches to production mail delivery. The remaining env
    // vars are auto-generated by the scaffold (see AUTO_GENERATED_ENV_VARS
    // in commands/create.ts) but still listed here so agent.yaml's `${VAR}`
    // interpolation has a registered key.
    expect(entry!.envVars).toEqual(
      expect.arrayContaining(["AUGGY_PUBLIC_URL", "VISITOR_SIGNING_KEY", "AUGGY_AGENT_ID"]),
    );
    expect(entry!.hasSkill).toBe(true);
  });

  it("resolves friendly augment aliases", () => {
    expect(resolveCatalogEntry("web-fetch")?.type).toBe("webFetch");
    expect(resolveCatalogEntry("visitor-auth")?.type).toBe("visitorAuth");
    expect(resolveCatalogEntry("telegram")?.type).toBe("telegramTransport");
    expect(resolveCatalogEntry("memory")?.type).toBe("layeredMemory");
    expect(resolveCatalogEntry("agent-mail")?.type).toBe("agentMail");
  });

  it("resolves canonical type names and legacy default-name aliases", () => {
    expect(resolveCatalogEntry("webFetch")?.defaultName).toBe("webFetch");
    expect(resolveCatalogEntry("turn-control")?.type).toBe("turnControl");
  });

  it("returns null for unknown augment specifiers and includes aliases in valid specifiers", () => {
    expect(resolveCatalogEntry("not-real")).toBeNull();
    expect(validAugmentSpecifiers()).toContain("web-fetch");
    expect(validAugmentSpecifiers()).toContain("webFetch");
  });
});
