import { describe, it, expect } from "bun:test";
import {
  AUGMENT_CATALOG,
  resolveCatalogEntry,
  validAugmentSpecifiers,
} from "../../src/cli/augment-catalog";

describe("augment catalog", () => {
  it("turnControl is registered in the catalog", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "turnControl");
    expect(entry).toBeDefined();
    expect(entry?.label).toMatch(/turn[- ]?control/i);
    expect(entry?.required).toBe(true);
    // After ADR-025 + PR α task 2, turnControl ships a bundled skill folder.
    expect(entry?.hasSkill).toBe(true);
  });

  it("turnControl uses its canonical type as defaultName", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "turnControl");
    expect(entry?.defaultName).toBe("turnControl");
  });

  it("catalog includes a visitorAuth entry with required env vars", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "visitorAuth");
    expect(entry).toBeTruthy();
    // AGENTMAIL_* are no longer listed by default — the catalog ships with
    // `agentMail.transport: "console"` so AgentMail creds aren't needed unless
    // the operator switches to production mail delivery. The remaining env
    // vars are auto-generated by the scaffold (see AUTO_GENERATED_ENV_VARS
    // in commands/create.ts) but still listed here so agent.yaml's `${VAR}`
    // interpolation has a registered key.
    expect(entry!.envVars).toEqual(
      expect.arrayContaining(["AUGGY_PUBLIC_URL", "VISITOR_SIGNING_KEY", "AUGGY_AGENT_ID"]),
    );
    expect(entry!.hasSkill).toBe(true);
  });

  it("catalog includes MCP as a preview augment with a bundled skill", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "mcp");
    expect(entry).toBeDefined();
    expect(entry?.defaultName).toBe("mcp");
    expect(entry?.stability).toBe("preview");
    expect(entry?.hasSkill).toBe(true);
  });

  it("catalog includes layeredMemory as stable production memory", () => {
    const entry = AUGMENT_CATALOG.find((e) => e.type === "layeredMemory");
    expect(entry).toBeDefined();
    expect(entry?.stability).toBe("stable");
    expect(entry?.defaultOptions).toMatchObject({
      dbPath: "./memory.db",
      autoSave: { enabled: false },
    });
    expect(entry?.hasSkill).toBe(true);
  });

  it("resolves canonical type names", () => {
    expect(resolveCatalogEntry("webFetch")?.defaultName).toBe("webFetch");
    expect(resolveCatalogEntry("turnControl")?.type).toBe("turnControl");
    expect(resolveCatalogEntry("visitorAuth")?.type).toBe("visitorAuth");
    expect(resolveCatalogEntry("layeredMemory")?.type).toBe("layeredMemory");
    expect(resolveCatalogEntry("agentMail")?.type).toBe("agentMail");
    expect(resolveCatalogEntry("mcp")?.type).toBe("mcp");
  });

  it("returns null for unknown or legacy augment specifiers", () => {
    expect(resolveCatalogEntry("not-real")).toBeNull();
    expect(resolveCatalogEntry("web-fetch")).toBeNull();
    expect(resolveCatalogEntry("memory")).toBeNull();
    expect(validAugmentSpecifiers()).not.toContain("web-fetch");
    expect(validAugmentSpecifiers()).toContain("webFetch");
  });
});
