import { describe, expect, test } from "bun:test";
import { createTypeScriptClient, type ClientRoutesReport } from "../../src/cli/routes-client";

function report(): ClientRoutesReport {
  return {
    agent: { name: "zip", configPath: "/tmp/zip/agent.yaml" },
    summary: {
      totalRoutes: 3,
      publicRoutes: 1,
      privateRoutes: 2,
      publicRoutePaths: ["GET /services/:serviceId"],
    },
    routes: [
      {
        method: "GET",
        path: "/services/:serviceId",
        augmentName: "concierge-services",
        auth: "none",
        params: ["serviceId"],
        public: true,
        security: "public",
        requestJsonSchema: {
          params: {
            type: "object",
            properties: { serviceId: { type: "string" } },
            required: ["serviceId"],
          },
          query: {
            type: "object",
            properties: {
              need: { type: "string" },
              tags: { type: "array", items: { type: "string" } },
              urgent: { type: "boolean" },
            },
            required: ["need"],
          },
        },
      },
      {
        method: "POST",
        path: "/leads/:leadId/notes",
        augmentName: "concierge-services",
        auth: "bearer",
        params: ["leadId"],
        public: false,
        security: "private",
        requestJsonSchema: {
          params: {
            type: "object",
            properties: { leadId: { type: "string" } },
            required: ["leadId"],
          },
          body: {
            type: "object",
            properties: {
              note: { type: "string" },
              priority: { enum: ["low", "high"] },
              score: { type: ["number", "null"] },
            },
            required: ["note"],
          },
        },
      },
      {
        method: "GET",
        path: "/me",
        augmentName: "visitor-profile",
        auth: "visitor.required",
        params: [],
        public: false,
        security: "private",
      },
    ],
  };
}

describe("createTypeScriptClient", () => {
  test("generates a self-contained TypeScript client from a route manifest", () => {
    const source = createTypeScriptClient(report());

    expect(source).toContain("Generated by auggy routes --client ts.");
    expect(source).toContain("do not ship creator bearer tokens to browser code");
    expect(source).toContain("export interface AuggyGetInputs");
    expect(source).toContain(
      '"/services/:serviceId": { params: { serviceId: string; }; query: { need: string; tags?: Array<string>; urgent?: boolean; }; };',
    );
    expect(source).toContain(
      '"/leads/:leadId/notes": { params: { leadId: string; }; body: { note: string; priority?: "low" | "high"; score?: number | null; }; };',
    );
    expect(source).toContain('"GET /services/:serviceId":');
    expect(source).toContain('auth: "visitor.required"');
    expect(source).toContain("export function createAuggyClient");

    const js = new Bun.Transpiler({ loader: "ts" }).transformSync(source);
    expect(js).toContain("function createAuggyClient");
  });

  test("emits empty input maps for agents with no routes", () => {
    const source = createTypeScriptClient({
      agent: { name: "empty", configPath: "/tmp/empty/agent.yaml" },
      summary: {
        totalRoutes: 0,
        publicRoutes: 0,
        privateRoutes: 0,
        publicRoutePaths: [],
      },
      routes: [],
    });

    expect(source).toContain("export interface AuggyGetInputs {}");
    expect(source).toContain("export interface AuggyPostInputs {}");
    expect(source).toContain("const ROUTES = {\n} as const;");
  });
});
