/*
 * Generated by auggy routes --client ts v0.
 * Do not edit manually.
 * createAuggyClient is emitted into this generated file; it is not a package export.
 * Target: browser.
 *
 * Browser clients omit creator/bearer/agent and webhook-policy routes. Do not ship privileged credentials to browser code.
 * Use visitor-token routes or public routes from browser clients.
 */

type TokenProvider = string | (() => string | undefined | Promise<string | undefined>);
type HeadersProvider = HeadersInit | (() => HeadersInit | Promise<HeadersInit>);

export interface AuggyClientConfig {
  baseUrl: string | URL;
  fetch?: typeof fetch;
  visitorToken?: TokenProvider;
  authAssertion?: TokenProvider;
  authAssertionHeader?: string;
  onVisitorToken?: (token: string) => void;
  headers?: HeadersProvider;
}

export interface AuggyRequestOptions {
  signal?: AbortSignal;
  headers?: HeadersInit;
}
type AuggyRequestArgs<TInput> = keyof TInput extends never
  ? [options?: AuggyRequestOptions]
  : {} extends TInput
    ? [input?: TInput, options?: AuggyRequestOptions] | [options: AuggyRequestOptions]
  : [input: TInput, options?: AuggyRequestOptions];

export type AuggyClientResult<TData = unknown> =
  | { ok: true; status: number; data: TData; response: Response; visitorToken?: string }
  | { ok: false; status: number; data: unknown; response: Response; visitorToken?: string };

type RouteInput = {
  params?: Record<string, unknown>;
  query?: Record<string, unknown>;
  body?: unknown;
};
type RouteCredentials = {
  bearerToken?: string;
  agentId?: string;
  agentSecret?: string;
  visitorToken?: string;
  authAssertion?: string;
};
type RouteMethod = "GET" | "POST";
type RouteAuth = "none" | "visitor.optional" | "visitor.required";
type AuthorizationConstraintValue = string | number | boolean | null | readonly AuthorizationConstraintValue[] | { readonly [key: string]: AuthorizationConstraintValue };
type AuthorizationResourceBinding = string | { param: string } | { input: string };
type RouteAuthorizationRequirement =
  | { scope: string }
  | { action: string; resource?: AuthorizationResourceBinding; constraints?: Readonly<Record<string, AuthorizationConstraintValue>> };
type RouteMeta = {
  method: RouteMethod;
  path: string;
  auth: RouteAuth;
  params: readonly string[];
  requires?: RouteAuthorizationRequirement | readonly RouteAuthorizationRequirement[];
};

export interface AuggyGetInputs {
  "/storefront/products": { query?: { q?: string; category?: "paddle" | "balls" | "bag"; playStyle?: "control" | "balanced" | "power"; maxPriceUsd?: number; }; };
  "/storefront/products/:id": { params: { id: string; }; };
}

export interface AuggyPostInputs {
  "/storefront/carts": { body: { items: Array<{ productId: string; quantity: number; }>; }; };
  "/storefront/checkout-sessions": { body: { cartId: string; email?: string; }; };
}

export interface AuggyGetOutputs {
  "/storefront/products": { products: Array<{ id: string; name: string; category: "paddle" | "balls" | "bag"; summary: string; priceUsd: number; playStyle?: "control" | "balanced" | "power"; level: "beginner" | "intermediate" | "advanced" | "all"; accent: string; inStock: boolean; }>; };
  "/storefront/products/:id": { product: { id: string; name: string; category: "paddle" | "balls" | "bag"; summary: string; priceUsd: number; playStyle?: "control" | "balanced" | "power"; level: "beginner" | "intermediate" | "advanced" | "all"; accent: string; inStock: boolean; }; };
}

export interface AuggyPostOutputs {
  "/storefront/carts": { cart: { id: string; items: Array<{ product: { id: string; name: string; category: "paddle" | "balls" | "bag"; summary: string; priceUsd: number; playStyle?: "control" | "balanced" | "power"; level: "beginner" | "intermediate" | "advanced" | "all"; accent: string; inStock: boolean; }; quantity: number; lineTotalUsd: number; }>; totalUsd: number; currency: "USD"; status: "draft"; }; };
  "/storefront/checkout-sessions": { checkout: { id: string; cartId: string; amountUsd: number; currency: "USD"; status: "requires_confirmation"; confirmationUrl: string; simulated: true; }; };
}

export type AuggyGetPath = keyof AuggyGetInputs;
export type AuggyPostPath = keyof AuggyPostInputs;

const ROUTES: Record<string, RouteMeta> = {
  "GET /storefront/products": { method: "GET", path: "/storefront/products", auth: "none", params: [] },
  "GET /storefront/products/:id": { method: "GET", path: "/storefront/products/:id", auth: "none", params: ["id"] },
  "POST /storefront/carts": { method: "POST", path: "/storefront/carts", auth: "visitor.optional", params: [] },
  "POST /storefront/checkout-sessions": { method: "POST", path: "/storefront/checkout-sessions", auth: "visitor.optional", params: [] },
};

export function createAuggyClient(config: AuggyClientConfig) {
  const fetchImpl = config.fetch ?? globalThis.fetch;
  if (!fetchImpl) {
    throw new Error("createAuggyClient requires a fetch implementation.");
  }

  return {
    get<Path extends AuggyGetPath>(
      path: Path,
      ...args: AuggyRequestArgs<AuggyGetInputs[Path]>
    ): Promise<AuggyClientResult<AuggyGetOutputs[Path]>> {
      const { input, options } = normalizeRequestArgs(args);
      return request(fetchImpl, config, "GET", path as string, input as RouteInput, options) as Promise<AuggyClientResult<AuggyGetOutputs[Path]>>;
    },
    post<Path extends AuggyPostPath>(
      path: Path,
      ...args: AuggyRequestArgs<AuggyPostInputs[Path]>
    ): Promise<AuggyClientResult<AuggyPostOutputs[Path]>> {
      const { input, options } = normalizeRequestArgs(args);
      return request(fetchImpl, config, "POST", path as string, input as RouteInput, options) as Promise<AuggyClientResult<AuggyPostOutputs[Path]>>;
    },
  };
}

async function request(
  fetchImpl: typeof fetch,
  config: AuggyClientConfig,
  method: "GET" | "POST",
  path: string,
  input: RouteInput,
  options: AuggyRequestOptions,
): Promise<AuggyClientResult> {
  const route = ROUTES[method + " " + path];
  if (!route) {
    throw new Error("Unknown Auggy route: " + method + " " + path);
  }

  const headers = new Headers(await resolveHeaders(config.headers));
  mergeHeaders(headers, options.headers);
  const credentials = await credentialsForRoute(config, route.auth);
  if (credentials.bearerToken) {
    headers.set("authorization", "Bearer " + credentials.bearerToken);
  }
  if (credentials.agentId) {
    headers.set("x-agent-id", credentials.agentId);
  }
  if (credentials.agentSecret) {
    headers.set("x-agent-secret", credentials.agentSecret);
  }
  if (credentials.visitorToken) {
    headers.set("x-visitor-token", credentials.visitorToken);
  }
  if (credentials.authAssertion) {
    headers.set(resolveAuthAssertionHeader(config.authAssertionHeader), credentials.authAssertion);
  }

  const url = buildUrl(config.baseUrl, route.path, route.params, input);
  const init: RequestInit = { method, headers, signal: options.signal };
  if (method === "POST" && Object.prototype.hasOwnProperty.call(input, "body")) {
    if (!headers.has("content-type")) headers.set("content-type", "application/json");
    init.body = JSON.stringify(input.body);
  }

  const response = await fetchImpl(url, init);
  const visitorToken = response.headers.get("x-visitor-token") ?? undefined;
  if (visitorToken) config.onVisitorToken?.(visitorToken);

  const data = await parseResponseData(response);
  const base = {
    status: response.status,
    data,
    response,
    ...(visitorToken ? { visitorToken } : {}),
  };
  if (response.ok) {
    return { ok: true, ...base };
  }
  return { ok: false, ...base };
}

function buildUrl(
  baseUrl: string | URL,
  pattern: string,
  params: readonly string[],
  input: RouteInput,
): URL {
  let path = pattern;
  for (const name of params) {
    const value = input.params?.[name];
    if (value === undefined || value === null || value === "") {
      throw new Error("Missing route param: " + name);
    }
    path = path.replace(":" + name, encodeURIComponent(String(value)));
  }

  const base = baseUrl instanceof URL ? baseUrl : new URL(String(baseUrl));
  const url = new URL(path, base);
  for (const [key, value] of Object.entries(input.query ?? {})) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item !== undefined && item !== null) url.searchParams.append(key, String(item));
      }
    } else {
      url.searchParams.append(key, String(value));
    }
  }
  return url;
}

async function credentialsForRoute(
  config: AuggyClientConfig,
  auth: RouteAuth,
): Promise<RouteCredentials> {
  if (auth === "visitor.required" || auth === "visitor.optional") {
    const authAssertion = await resolveToken(config.authAssertion);
    const credentials: RouteCredentials = authAssertion ? { authAssertion } : {};
    if (!authAssertion) {
      const token = await resolveToken(config.visitorToken);
      if (token) credentials.visitorToken = token;
    }
    if (auth === "visitor.required" && !credentials.visitorToken && !credentials.authAssertion) {
      throw new Error("This Auggy route requires a visitorToken or authAssertion.");
    }
    return credentials;
  }
  return {};
}

function normalizeRequestArgs(args: readonly unknown[]): {
  input: RouteInput;
  options: AuggyRequestOptions;
} {
  const first = args[0];
  const second = args[1];
  if (second !== undefined) {
    return { input: (first ?? {}) as RouteInput, options: second as AuggyRequestOptions };
  }
  if (isRequestOptions(first) && !isRouteInput(first)) {
    return { input: {}, options: first };
  }
  return { input: (first ?? {}) as RouteInput, options: {} };
}

function isRouteInput(value: unknown): value is RouteInput {
  return isRecord(value) && ("params" in value || "query" in value || "body" in value);
}

function isRequestOptions(value: unknown): value is AuggyRequestOptions {
  return isRecord(value) && ("signal" in value || "headers" in value);
}

async function resolveToken(provider: TokenProvider | undefined): Promise<string | undefined> {
  if (typeof provider === "function") return provider();
  return provider;
}

function resolveAuthAssertionHeader(value: string | undefined): string {
  const header = value?.trim().toLowerCase() ?? "x-auggy-auth-assertion";
  const reserved = [
    "authorization", "content-type", "idempotency-key", "x-agent-id", "x-agent-secret",
    "x-auggy-console-internal", "x-org-id", "x-peer-id", "x-peer-kind", "x-peer-name",
    "x-visitor-token", "x-forwarded-for", "x-forwarded-host", "x-forwarded-port",
    "x-forwarded-proto", "x-real-ip",
  ];
  try {
    new Headers([[header, "assertion"]]);
  } catch {
    throw new Error("authAssertionHeader must be a non-reserved x-* HTTP header name.");
  }
  if (!header.startsWith("x-") || reserved.includes(header)) {
    throw new Error("authAssertionHeader must be a non-reserved x-* HTTP header name.");
  }
  return header;
}


async function resolveHeaders(provider: HeadersProvider | undefined): Promise<HeadersInit | undefined> {
  if (typeof provider === "function") return provider();
  return provider;
}

function mergeHeaders(headers: Headers, extra: HeadersInit | undefined): void {
  if (!extra) return;
  new Headers(extra).forEach((value, key) => headers.set(key, value));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

async function parseResponseData(response: Response): Promise<unknown> {
  if (response.status === 204) return undefined;
  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.toLowerCase().includes("application/json")) return response.json();
  return response.text();
}

export type AuggyClient = ReturnType<typeof createAuggyClient>;
export type AuggyGetResult<Path extends AuggyGetPath> = AuggyClientResult<AuggyGetOutputs[Path]>;
export type AuggyPostResult<Path extends AuggyPostPath> = AuggyClientResult<AuggyPostOutputs[Path]>;
