import type { RouteManifestEntry, RouteManifestSummary } from "../kernel/route-manifest";

type JsonObject = Record<string, unknown>;
const GENERATED_CLIENT_VERSION = "v0";

export interface ClientRoutesReport {
  agent: {
    name: string;
    configPath: string;
  };
  summary: RouteManifestSummary;
  routes: readonly RouteManifestEntry[];
}

export type TypeScriptClientTarget = "browser" | "server";

export interface TypeScriptClientOptions {
  target?: TypeScriptClientTarget;
}

export function createTypeScriptClient(
  report: ClientRoutesReport,
  opts: TypeScriptClientOptions = {},
): string {
  const target = opts.target ?? "browser";
  const allRoutes = [...report.routes].sort((a, b) => {
    const left = `${a.method} ${a.path}`;
    const right = `${b.method} ${b.path}`;
    return left.localeCompare(right);
  });
  const routes = allRoutes.filter((route) => routeSupportsTarget(route, target));
  const skippedRoutes = allRoutes.filter((route) => !routeSupportsTarget(route, target));

  return [
    clientHeader(target, skippedRoutes),
    "",
    "type TokenProvider = string | (() => string | undefined | Promise<string | undefined>);",
    "type HeadersProvider = HeadersInit | (() => HeadersInit | Promise<HeadersInit>);",
    ...(target === "server"
      ? [
          "export interface AuggyAgentCredentials {",
          "  agentId: string;",
          "  agentSecret: string;",
          "}",
          "type AgentCredentialsProvider = AuggyAgentCredentials | (() => AuggyAgentCredentials | undefined | Promise<AuggyAgentCredentials | undefined>);",
        ]
      : []),
    "",
    clientConfig(target),
    "",
    "export interface AuggyRequestOptions {",
    "  signal?: AbortSignal;",
    "  headers?: HeadersInit;",
    "}",
    "type AuggyRequestArgs<TInput> = keyof TInput extends never",
    "  ? [options?: AuggyRequestOptions]",
    "  : {} extends TInput",
    "    ? [input?: TInput, options?: AuggyRequestOptions] | [options: AuggyRequestOptions]",
    "  : [input: TInput, options?: AuggyRequestOptions];",
    "",
    "export type AuggyClientResult<TData = unknown> =",
    "  | { ok: true; status: number; data: TData; response: Response; visitorToken?: string }",
    "  | { ok: false; status: number; data: unknown; response: Response; visitorToken?: string };",
    "",
    "type RouteInput = {",
    "  params?: Record<string, unknown>;",
    "  query?: Record<string, unknown>;",
    "  body?: unknown;",
    "};",
    "type RouteCredentials = {",
    "  bearerToken?: string;",
    "  agentId?: string;",
    "  agentSecret?: string;",
    "  visitorToken?: string;",
    "  authAssertion?: string;",
    "};",
    'type RouteMethod = "GET" | "POST";',
    `type RouteAuth = ${routeAuthUnion(target)};`,
    "type RouteMeta = {",
    "  method: RouteMethod;",
    "  path: string;",
    "  auth: RouteAuth;",
    "  params: readonly string[];",
    "};",
    "",
    routeInputMap(
      "AuggyGetInputs",
      routes.filter((route) => route.method === "GET"),
    ),
    "",
    routeInputMap(
      "AuggyPostInputs",
      routes.filter((route) => route.method === "POST"),
    ),
    "",
    routeOutputMap(
      "AuggyGetOutputs",
      routes.filter((route) => route.method === "GET"),
    ),
    "",
    routeOutputMap(
      "AuggyPostOutputs",
      routes.filter((route) => route.method === "POST"),
    ),
    "",
    "export type AuggyGetPath = keyof AuggyGetInputs;",
    "export type AuggyPostPath = keyof AuggyPostInputs;",
    "",
    routeTable(routes),
    "",
    runtimeSource(target),
    "",
    clientTypeExports(),
    "",
  ].join("\n");
}

function clientHeader(
  target: TypeScriptClientTarget,
  skippedRoutes: readonly RouteManifestEntry[],
): string {
  const lines = [
    "/*",
    ` * Generated by auggy routes --client ts ${GENERATED_CLIENT_VERSION}.`,
    " * Do not edit manually.",
    ` * Target: ${target}.`,
    " *",
    ...(target === "browser"
      ? [
          " * Browser clients omit creator/bearer/agent routes. Do not ship privileged credentials to browser code.",
          " * Use visitor-token routes or public routes from browser clients.",
        ]
      : [
          " * Server clients include creator/bearer and agent routes for server-side and SSR callers.",
          " * Do not bundle this generated file into browser code with bearer or agent credentials.",
        ]),
  ];

  if (skippedRoutes.length > 0) {
    lines.push(" *", " * Routes omitted for this target:");
    for (const route of skippedRoutes.slice(0, 20)) {
      lines.push(` * - ${route.method} ${route.path} auth=${route.auth}`);
    }
    if (skippedRoutes.length > 20) {
      lines.push(` * - ...and ${skippedRoutes.length - 20} more`);
    }
  }

  lines.push(" */");
  return lines.join("\n");
}

function clientConfig(target: TypeScriptClientTarget): string {
  return [
    "export interface AuggyClientConfig {",
    "  baseUrl: string | URL;",
    "  fetch?: typeof fetch;",
    ...(target === "server"
      ? ["  bearerToken?: TokenProvider;", "  agentCredentials?: AgentCredentialsProvider;"]
      : [
          "  visitorToken?: TokenProvider;",
          "  authAssertion?: TokenProvider;",
          "  onVisitorToken?: (token: string) => void;",
        ]),
    "  headers?: HeadersProvider;",
    "}",
  ].join("\n");
}

function routeInputMap(name: string, routes: readonly RouteManifestEntry[]): string {
  if (routes.length === 0) {
    return `export interface ${name} {}`;
  }

  return [
    `export interface ${name} {`,
    ...routes.map((route) => `  ${JSON.stringify(route.path)}: ${inputTypeForRoute(route)};`),
    "}",
  ].join("\n");
}

function inputTypeForRoute(route: RouteManifestEntry): string {
  const fields: string[] = [];

  if (route.params.length > 0) {
    fields.push(`params: ${paramsTypeForRoute(route)};`);
  }

  if (route.requestJsonSchema?.query) {
    const queryRequired = requiredProperties(route.requestJsonSchema.query).size > 0;
    fields.push(
      `query${queryRequired ? "" : "?"}: ${schemaToType(route.requestJsonSchema.query)};`,
    );
  }

  if (route.requestJsonSchema?.body) {
    fields.push(`body: ${schemaToType(route.requestJsonSchema.body)};`);
  }

  return fields.length > 0 ? `{ ${fields.join(" ")} }` : "{}";
}

function routeOutputMap(name: string, routes: readonly RouteManifestEntry[]): string {
  if (routes.length === 0) {
    return `export interface ${name} {}`;
  }

  return [
    `export interface ${name} {`,
    ...routes.map(
      (route) =>
        `  ${JSON.stringify(route.path)}: ${route.responseJsonSchema ? schemaToType(route.responseJsonSchema) : "unknown"};`,
    ),
    "}",
  ].join("\n");
}

function paramsTypeForRoute(route: RouteManifestEntry): string {
  const paramsSchema = route.requestJsonSchema?.params;
  const properties = schemaProperties(paramsSchema);
  const fields = route.params.map((name) => {
    const property = properties?.[name];
    return `${propertyName(name)}: ${property ? schemaToType(property) : "string"};`;
  });
  return `{ ${fields.join(" ")} }`;
}

function routeTable(routes: readonly RouteManifestEntry[]): string {
  const entries = routes.map(
    (route) =>
      `  ${JSON.stringify(routeKey(route))}: { method: ${JSON.stringify(
        route.method,
      )}, path: ${JSON.stringify(route.path)}, auth: ${JSON.stringify(
        route.auth,
      )}, params: ${JSON.stringify(route.params)} },`,
  );

  return ["const ROUTES: Record<string, RouteMeta> = {", ...entries, "};"].join("\n");
}

function runtimeSource(target: TypeScriptClientTarget): string {
  return `export function createAuggyClient(config: AuggyClientConfig) {
  const fetchImpl = config.fetch ?? globalThis.fetch;
  if (!fetchImpl) {
    throw new Error("createAuggyClient requires a fetch implementation.");
  }

  return {
    get<Path extends AuggyGetPath>(
      path: Path,
      ...args: AuggyRequestArgs<AuggyGetInputs[Path]>
    ): Promise<AuggyClientResult<AuggyGetOutputs[Path]>> {
      const { input, options } = normalizeRequestArgs(args);
      return request(fetchImpl, config, "GET", path as string, input as RouteInput, options) as Promise<AuggyClientResult<AuggyGetOutputs[Path]>>;
    },
    post<Path extends AuggyPostPath>(
      path: Path,
      ...args: AuggyRequestArgs<AuggyPostInputs[Path]>
    ): Promise<AuggyClientResult<AuggyPostOutputs[Path]>> {
      const { input, options } = normalizeRequestArgs(args);
      return request(fetchImpl, config, "POST", path as string, input as RouteInput, options) as Promise<AuggyClientResult<AuggyPostOutputs[Path]>>;
    },
  };
}

async function request(
  fetchImpl: typeof fetch,
  config: AuggyClientConfig,
  method: "GET" | "POST",
  path: string,
  input: RouteInput,
  options: AuggyRequestOptions,
): Promise<AuggyClientResult> {
  const route = ROUTES[method + " " + path];
  if (!route) {
    throw new Error("Unknown Auggy route: " + method + " " + path);
  }

  const headers = new Headers(await resolveHeaders(config.headers));
  mergeHeaders(headers, options.headers);
  const credentials = await credentialsForRoute(config, route.auth);
  if (credentials.bearerToken) {
    headers.set("authorization", "Bearer " + credentials.bearerToken);
  }
  if (credentials.agentId) {
    headers.set("x-agent-id", credentials.agentId);
  }
  if (credentials.agentSecret) {
    headers.set("x-agent-secret", credentials.agentSecret);
  }
  ${
    target === "browser"
      ? `if (credentials.visitorToken) {
    headers.set("x-visitor-token", credentials.visitorToken);
  }
  if (credentials.authAssertion) {
    headers.set("x-auggy-auth-assertion", credentials.authAssertion);
  }`
      : ""
  }

  const url = buildUrl(config.baseUrl, route.path, route.params, input);
  const init: RequestInit = { method, headers, signal: options.signal };
  if (method === "POST" && Object.prototype.hasOwnProperty.call(input, "body")) {
    if (!headers.has("content-type")) headers.set("content-type", "application/json");
    init.body = JSON.stringify(input.body);
  }

  const response = await fetchImpl(url, init);
  ${
    target === "browser"
      ? `const visitorToken = response.headers.get("x-visitor-token") ?? undefined;
  if (visitorToken) config.onVisitorToken?.(visitorToken);`
      : "const visitorToken = undefined;"
  }

  const data = await parseResponseData(response);
  const base = {
    status: response.status,
    data,
    response,
    ...(visitorToken ? { visitorToken } : {}),
  };
  if (response.ok) {
    return { ok: true, ...base };
  }
  return { ok: false, ...base };
}

function buildUrl(
  baseUrl: string | URL,
  pattern: string,
  params: readonly string[],
  input: RouteInput,
): URL {
  let path = pattern;
  for (const name of params) {
    const value = input.params?.[name];
    if (value === undefined || value === null || value === "") {
      throw new Error("Missing route param: " + name);
    }
    path = path.replace(":" + name, encodeURIComponent(String(value)));
  }

  const base = baseUrl instanceof URL ? baseUrl : new URL(String(baseUrl));
  const url = new URL(path, base);
  for (const [key, value] of Object.entries(input.query ?? {})) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item !== undefined && item !== null) url.searchParams.append(key, String(item));
      }
    } else {
      url.searchParams.append(key, String(value));
    }
  }
  return url;
}

async function credentialsForRoute(
  config: AuggyClientConfig,
  auth: RouteAuth,
): Promise<RouteCredentials> {
  ${
    target === "server"
      ? `if (auth === "bearer" || auth === "creator") {
    const token = await resolveToken(config.bearerToken);
    if (!token) throw new Error("This Auggy route requires a bearerToken.");
    return { bearerToken: token };
  }
  if (auth === "agent.required") {
    const credentials = await resolveAgentCredentials(config.agentCredentials);
    if (!credentials?.agentId || !credentials.agentSecret) {
      throw new Error("This Auggy route requires agentCredentials.");
    }
    return { agentId: credentials.agentId, agentSecret: credentials.agentSecret };
  }`
      : `if (auth === "visitor.required" || auth === "visitor.optional") {
    const authAssertion = await resolveToken(config.authAssertion);
    const credentials: RouteCredentials = authAssertion ? { authAssertion } : {};
    const token = await resolveToken(config.visitorToken);
    if (token) credentials.visitorToken = token;
    if (auth === "visitor.required" && !credentials.visitorToken && !credentials.authAssertion) {
      throw new Error("This Auggy route requires a visitorToken or authAssertion.");
    }
    return credentials;
  }`
  }
  return {};
}

function normalizeRequestArgs(args: readonly unknown[]): {
  input: RouteInput;
  options: AuggyRequestOptions;
} {
  const first = args[0];
  const second = args[1];
  if (second !== undefined) {
    return { input: (first ?? {}) as RouteInput, options: second as AuggyRequestOptions };
  }
  if (isRequestOptions(first) && !isRouteInput(first)) {
    return { input: {}, options: first };
  }
  return { input: (first ?? {}) as RouteInput, options: {} };
}

function isRouteInput(value: unknown): value is RouteInput {
  return isRecord(value) && ("params" in value || "query" in value || "body" in value);
}

function isRequestOptions(value: unknown): value is AuggyRequestOptions {
  return isRecord(value) && ("signal" in value || "headers" in value);
}

async function resolveToken(provider: TokenProvider | undefined): Promise<string | undefined> {
  if (typeof provider === "function") return provider();
  return provider;
}
${
  target === "server"
    ? `
async function resolveAgentCredentials(provider: AgentCredentialsProvider | undefined): Promise<AuggyAgentCredentials | undefined> {
  if (typeof provider === "function") return provider();
  return provider;
}`
    : ""
}

async function resolveHeaders(provider: HeadersProvider | undefined): Promise<HeadersInit | undefined> {
  if (typeof provider === "function") return provider();
  return provider;
}

function mergeHeaders(headers: Headers, extra: HeadersInit | undefined): void {
  if (!extra) return;
  new Headers(extra).forEach((value, key) => headers.set(key, value));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

async function parseResponseData(response: Response): Promise<unknown> {
  if (response.status === 204) return undefined;
  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.toLowerCase().includes("application/json")) return response.json();
  return response.text();
}`;
}

function clientTypeExports(): string {
  return [
    "export type AuggyClient = ReturnType<typeof createAuggyClient>;",
    "export type AuggyGetResult<Path extends AuggyGetPath> = AuggyClientResult<AuggyGetOutputs[Path]>;",
    "export type AuggyPostResult<Path extends AuggyPostPath> = AuggyClientResult<AuggyPostOutputs[Path]>;",
  ].join("\n");
}

function routeAuthUnion(target: TypeScriptClientTarget): string {
  if (target === "server") return '"bearer" | "creator" | "agent.required" | "none"';
  return '"none" | "visitor.optional" | "visitor.required"';
}

function routeSupportsTarget(route: RouteManifestEntry, target: TypeScriptClientTarget): boolean {
  if (route.auth === "none") return true;
  if (route.auth === "bearer" || route.auth === "creator" || route.auth === "agent.required") {
    return target === "server";
  }
  return target === "browser";
}

function schemaToType(schema: unknown): string {
  if (!isRecord(schema)) return "unknown";

  const union = unionSchemas(schema);
  if (union) {
    return union.map((item) => schemaToType(item)).join(" | ");
  }

  const enumValues = schema.enum;
  if (Array.isArray(enumValues) && enumValues.length > 0) {
    return enumValues.map((value) => literalType(value)).join(" | ");
  }

  if (Object.hasOwn(schema, "const")) {
    return literalType(schema.const);
  }

  const nullable = schema.nullable === true;
  const schemaType = schema.type;
  if (Array.isArray(schemaType)) {
    const nonNullTypes = schemaType.filter((type) => type !== "null");
    const nullType = schemaType.length !== nonNullTypes.length ? " | null" : "";
    if (nonNullTypes.length === 1) {
      return `${typeKeyword(nonNullTypes[0], schema)}${nullType}`;
    }
    return `${nonNullTypes.map((type) => typeKeyword(type, schema)).join(" | ")}${nullType}`;
  }

  const base = typeKeyword(schemaType, schema);
  return nullable && base !== "null" ? `${base} | null` : base;
}

function typeKeyword(type: unknown, schema: JsonObject): string {
  if (type === "string") return "string";
  if (type === "number" || type === "integer") return "number";
  if (type === "boolean") return "boolean";
  if (type === "null") return "null";
  if (type === "array") return `Array<${schemaToType(schema.items)}>`;
  if (type === "object" || schemaProperties(schema)) return objectType(schema);
  return "unknown";
}

function objectType(schema: JsonObject): string {
  const properties = schemaProperties(schema);
  if (!properties) {
    const additionalProperties = schema.additionalProperties;
    if (isRecord(additionalProperties))
      return `Record<string, ${schemaToType(additionalProperties)}>`;
    return additionalProperties === false ? "{}" : "Record<string, unknown>";
  }

  const required = requiredProperties(schema);
  const fields = Object.entries(properties).map(
    ([name, property]) =>
      `${propertyName(name)}${required.has(name) ? "" : "?"}: ${schemaToType(property)};`,
  );
  return `{ ${fields.join(" ")} }`;
}

function unionSchemas(schema: JsonObject): unknown[] | undefined {
  const anyOf = schema.anyOf;
  if (Array.isArray(anyOf) && anyOf.length > 0) return anyOf;
  const oneOf = schema.oneOf;
  if (Array.isArray(oneOf) && oneOf.length > 0) return oneOf;
  return undefined;
}

function literalType(value: unknown): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean" || value === null) {
    return JSON.stringify(value);
  }
  return "unknown";
}

function schemaProperties(schema: unknown): Record<string, unknown> | undefined {
  if (!isRecord(schema)) return undefined;
  const properties = schema.properties;
  return isRecord(properties) ? properties : undefined;
}

function requiredProperties(schema: unknown): Set<string> {
  if (!isRecord(schema)) return new Set();
  const required = schema.required;
  return new Set(
    Array.isArray(required) ? required.filter((name) => typeof name === "string") : [],
  );
}

function propertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function routeKey(route: RouteManifestEntry): string {
  return `${route.method} ${route.path}`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
