import { Context } from "@temporalio/activity";
import { ApplicationFailure } from "@temporalio/common";

import {
  AuggyRunError,
  createAuggyRunClient,
  type AuggyRunClient,
  type AuggyRunClientConfig,
} from "./auggy-client.js";

export interface OrderSupportActivityInput {
  /** Generated by the deterministic Workflow from its stable Workflow ID. */
  idempotencyKey: string;
  threadId: string;
  message: string;
}
export type OrderSupportActivityOutcome =
  | { state: "completed"; runId: string }
  | { state: "auth-required" }
  | { state: "binding-conflict" }
  | { state: "failed" }
  | { state: "input-required" }
  | { state: "outcome-unknown" }
  | { state: "rejected" }
  | { state: "remote-canceled" };

export interface OrderSupportActivities {
  requestOrderSupportReview(input: OrderSupportActivityInput): Promise<OrderSupportActivityOutcome>;
}

interface ActivityContext {
  heartbeat(): void;
  cancellationSignal: AbortSignal;
  cancelled: Promise<never>;
}

export interface OrderSupportActivityDependencies {
  client?: AuggyRunClient;
  currentContext?: () => ActivityContext;
  now?: () => number;
}

/**
 * The token and target live only in the Worker process. The Activity returns
 * neither model text nor an HTTP body, avoiding an unnecessary copy in
 * Temporal history.
 */
export function createOrderSupportActivities(
  config: AuggyRunClientConfig,
  dependencies: OrderSupportActivityDependencies = {},
): OrderSupportActivities {
  const client = dependencies.client ?? createAuggyRunClient(config);
  const currentContext = dependencies.currentContext ?? (() => Context.current());
  const now = dependencies.now ?? Date.now;

  return {
    async requestOrderSupportReview(input) {
      const context = currentContext();
      let lastHeartbeatAt = 0;
      const heartbeat = () => {
        const currentTime = now();
        if (currentTime - lastHeartbeatAt < 5_000) return;
        lastHeartbeatAt = currentTime;
        // Do not attach prompt, response, token, or idempotency-key details.
        context.heartbeat();
      };

      heartbeat();
      try {
        const result = await client.run(input, context.cancellationSignal, heartbeat);
        return { state: "completed", runId: result.runId };
      } catch (error) {
        if (!(error instanceof AuggyRunError)) return { state: "outcome-unknown" };
        if (error.kind === "local-canceled" && context.cancellationSignal.aborted) {
          // `cancelled` rejects with Temporal's CancelledFailure. The request
          // has only been disconnected; Auggy's keyed execution may continue.
          return context.cancelled;
        }
        if (error.retryable) {
          // Activity retries retain the identical input and idempotency key.
          throw ApplicationFailure.retryable("Auggy request did not reach a terminal result", "AuggyRetryable");
        }
        switch (error.kind) {
          case "binding-conflict":
            return { state: "binding-conflict" };
          case "auth-required":
            return { state: "auth-required" };
          case "input-required":
            return { state: "input-required" };
          case "task-failed":
            return { state: "failed" };
          case "remote-canceled":
            return { state: "remote-canceled" };
          case "rejected":
            return { state: "rejected" };
          default:
            // A stream limit, malformed terminal event, or server-declared
            // ambiguity must be reconciled by business logic, not replayed.
            return { state: "outcome-unknown" };
        }
      }
    },
  };
}
