import { Context } from "@temporalio/activity";
import { ApplicationFailure } from "@temporalio/common";

import { AuggyRunError, createAuggyRunClient, type AuggyRunClientConfig } from "./auggy-client.js";

export interface OrderSupportActivityInput {
  /** Generated by the deterministic Workflow from its stable Workflow ID. */
  idempotencyKey: string;
  threadId: string;
  message: string;
}
export type OrderSupportActivityOutcome =
  | { state: "completed"; runId: string | null }
  | { state: "binding-conflict" }
  | { state: "outcome-unknown" }
  | { state: "rejected" };

export interface OrderSupportActivities {
  requestOrderSupportReview(input: OrderSupportActivityInput): Promise<OrderSupportActivityOutcome>;
}

/**
 * The token and target live only in the Worker process. The Activity returns
 * neither model text nor an HTTP body, avoiding an unnecessary copy in
 * Temporal history.
 */
export function createOrderSupportActivities(config: AuggyRunClientConfig): OrderSupportActivities {
  const client = createAuggyRunClient(config);

  return {
    async requestOrderSupportReview(input) {
      const context = Context.current();
      let lastHeartbeatAt = 0;
      const heartbeat = () => {
        const now = Date.now();
        if (now - lastHeartbeatAt < 5_000) return;
        lastHeartbeatAt = now;
        // Do not attach prompt, response, token, or idempotency-key details.
        context.heartbeat();
      };

      heartbeat();
      try {
        const result = await client.run(input, context.cancellationSignal, heartbeat);
        return { state: "completed", runId: result.runId };
      } catch (error) {
        if (!(error instanceof AuggyRunError)) return { state: "outcome-unknown" };
        if (error.kind === "canceled") {
          // `cancelled` rejects with Temporal's CancelledFailure. The request
          // has only been disconnected; Auggy's keyed execution may continue.
          return context.cancelled;
        }
        if (error.retryable) {
          // Activity retries retain the identical input and idempotency key.
          throw ApplicationFailure.retryable("Auggy request did not reach a terminal result", "AuggyRetryable");
        }
        switch (error.kind) {
          case "binding-conflict":
            return { state: "binding-conflict" };
          case "rejected":
            return { state: "rejected" };
          default:
            // A stream limit, malformed terminal event, or server-declared
            // ambiguity must be reconciled by business logic, not replayed.
            return { state: "outcome-unknown" };
        }
      }
    },
  };
}
